failure-threshold: warning # name of threshold level (error | warning | info | style | ignore | none)
format: tty # Output format (tty | json | checkstyle | codeclimate | gitlab_codeclimate | gnu | codacy)
ignored:
  - DL3001 # list of rules
no-color: false # true | false
no-fail: false # true | false
strict-labels: false # true | false
disable-ignore-pragma: false # true | false
