# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
BASH_SHELLCHECK_ARGUMENTS: -e "SC2162"
CLEAR_REPORT_FOLDER: true
DISABLE_ERRORS: false
DOCKERFILE_HADOLINT_CONFIG_FILE: .hadolint.yml
DOCKERFILE_HADOLINT_RULES_PATH: .linters
ENABLE_LINTERS:
  - BASH_EXEC
  - BASH_SHELLCHECK
  - MAKEFILE_CHECKMAKE
  - PYTHON_BLACK
  - PYTHON_BANDIT
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - SQL_SQL_LINT
  - SQL_SQLFLUFF
  - SQL_TSQLLINT
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - YAML_PRETTIER
  - YAML_V8R
  - DOCKERFILE_HADOLINT

FAIL_IF_UPDATED_SOURCES: false
FILEIO_REPORTER: false
FILTER_REGEX_EXCLUDE: none
FORMATTERS_DISABLE_ERRORS: false
IGNORE_GITIGNORED_FILES: true
LINTER_RULES_PATH: .linters # Directory for all linter configuration rules.
LOG_LEVEL: INFO
MARKDOWN_DEFAULT_STYLE: markdownlint
PARALLEL: true
PRINT_ALPACA: false
PYTHON_BANDIT_RULES_PATH: .linters
PYTHON_BANDIT_CONFIG_FILE: .bandit.yml
PYTHON_FLAKE8_RULES_PATH: .linters
SHOW_ELAPSED_TIME: true
SHOW_SKIPPED_LINTERS: true
SQL_SQLFLUFF_RULES_PATH: .linters
